import type { Metadata } from "next";
import { AuthCTXProvider } from "../../context/AuthContext";
import { AddCTXProvider } from "../../context/AddContext";
import { SubtractCTXProvider } from "../../context/SubtractContext";
import { MultiplyCTXProvider } from "../../context/MultiplyContext";
import { DivideCTXProvider } from "../../context/DivideContext";
import "./globals.css";

export const metadata: Metadata = {
  title: "React Contexts",
  description: "Generated by Rana Rabees",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AuthCTXProvider>
          <AddCTXProvider>
            <SubtractCTXProvider>
              <MultiplyCTXProvider>
                <DivideCTXProvider>
                  {children}
                </DivideCTXProvider>
              </MultiplyCTXProvider>
            </SubtractCTXProvider>
          </AddCTXProvider>
        </AuthCTXProvider>
      </body>
    </html>
  );
}

